name: Development Approval Workflow

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    name: Build HTML & PDF Resume Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          build_pdf: true
          build_html: false
          table_of_contents: false
          input_path: RESUME.md
          output_dir: /
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: RESUME.pdf
          if-no-files-found: error
