name: Development Approval Workflow

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  convert:
    name: Build HTML & PDF Resume Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          build_pdf: true
          build_html: true
          table_of_contents: false
          input_path: RESUME.md
          output_dir: /
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: RESUME.html
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: RESUME.pdf
          if-no-files-found: error
      - uses: actions/github-script@v6
        name: Delete Previous Release
        continue-on-error: true
        with:
          script: |
            try {
              const data = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: "dev"
              });
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: data.id
              });
            } catch (e) {
              console.log(e);
            }
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "tags/dev"
              });
            } catch (e) {
              console.log(e);
            }
      - uses: actions/github-script@v6
        name: Create New Release
        with:
          script: |
            const tag = 'dev';
            const commit = context.sha;
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: commit
            });
            const fs = require('fs');
            const path = require('path');
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              body: 'Latest Development Release',
              draft: true,
              prerelease: true
            });
            const pdf = fs.readFileSync(path.basename('./RESUME.pdf'));
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: 'RESUME.pdf',
              data: pdf
              headers: {
                'content-length': pdf.length,
                'content-type': 'application/pdf'
              }
            });
            const html = fs.readFileSync(path.basename('./RESUME.html'));
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: 'RESUME.html',
              data: html
              headers: {
                'content-length': html.length,
                'content-type': 'text/html'
              }
            });
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              draft: false
            });


      # - id: branch
      #   run: |
      #       echo branch=$(git branch --show-current) >> $GITHUB_ENV
      # - uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: false
      #     artifacts: "RESUME.pdf,RESUME.html"
      #     prerelease: true
      #     draft: false
      #     commit: ${{ env.branch }}
      #     tag: "dev"
      #     makeLatest: false
